### ISSUE TITLE
conflict between csvsimple and ctable?

### ISSUE THREAD

**Issue by alan-isaac** [T-F-S/csvsimple#9]
The following MWE produces an error upon compilation:

```
\documentclass{article}
\usepackage{ctable} 
\usepackage{csvsimple}
\begin{document}
test
\end{document} 
```

The error is:

```
! Undefined control sequence.
\pgfutil@addpdfresource@extgs ...urce@extgs@plain 
                                                  {#1}
```

**Comment by T-F-S** [comment]
This is not a `csvsimple` problem, but a conflict between `ctable` and `pgfrcs` which loads `pgfutil-common.tex`. Also see https://tex.stackexchange.com/a/536744

An MWE to show the error is

```latex
\documentclass{article}
\usepackage{ctable}
\usepackage{pgfrcs}

\begin{document}
test
\end{document}
```

`ctable` seems to have a `tikz` detection, but fails to detect `pgf`. One gets a package error, if `tikz` is loaded after `ctable`.

A workaround is to load `tikz` additionally before `ctable`:

```latex
\documentclass{article}
\usepackage{tikz}
\usepackage{ctable}
\usepackage{csvsimple}

\begin{document}
test
\end{document}
```

Maybe, you should contact the author of `ctable` to detect `pgfrcs` instead of / additional to `tikz`.
